FROM postgres:version # colocar la version

# Instalar el cliente de PostgreSQL para soporte adicional en healthcheck
RUN apt-get update && apt-get install -y postgresql-client

# Exponer el puerto estándar de PostgreSQL
EXPOSE port # coloca el puerto donde dice port

# Copiar el script de inicialización (opcional)
# COPY init.sql /docker-entrypoint-initdb.d/

# Healthcheck para PostgreSQL
HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD pg_isready -U usuario_postgres # colocar usuario en usuario-postgres
